language: c
sudo: false
env:
  global:
    - RACKET_DIR=~/racket
    - DEPLOY_VERSION="6.4"
  matrix:
    - RACKET_VERSION="6.4" CATALOG_VERSION="6.4"
    - RACKET_VERSION="HEAD" CATALOG_VERSION="6.4"
matrix:
  allow_failures:
    - env: RACKET_VERSION="HEAD" CATALOG_VERSION="6.4"
before_install:
  - git clone https://github.com/greghendershott/travis-racket.git ../travis-racket
  - cat ../travis-racket/install-racket.sh | bash
  - 'export PATH="${RACKET_DIR}/bin:${PATH}"'
  - export VERSION_SPECIFIC_CATALOG="http://download.racket-lang.org/releases/${CATALOG_VERSION}/catalog/"
  - raco pkg config --set catalogs $VERSION_SPECIFIC_CATALOG http://pkgs.racket-lang.org http://planet-compats.racket-lang.org
  - if [ "${DEPLOY_VERSION}" == "${RACKET_VERSION}" ]; then raco pkg install --deps search-auto cover; fi
  - if [ "${DEPLOY_VERSION}" == "${RACKET_VERSION}" ]; then raco pkg install --deps search-auto cover-coveralls; fi
install:
  - raco pkg install --auto $TRAVIS_BUILD_DIR
script:
  - raco test $TRAVIS_BUILD_DIR
  - if [ "${DEPLOY_VERSION}" == "${RACKET_VERSION}" ]; then raco cover -f coveralls -d $TRAVIS_BUILD_DIR/coverage .; fi
after_success:
  - echo "Starting deploy"
  - if [ "${DEPLOY_VERSION}" != "${RACKET_VERSION}" ]; then exit 0; fi
  - if [ "${TRAVIS_BRANCH}" != "master" ]; then exit 0; fi
  - if [ "${TRAVIS_PULL_REQUEST}" != "false" ]; then exit 0; fi
  - rm -rf out || exit 0;
  - mkdir out;
  - echo "In out dir"
  - raco scribble --dest out --dest-name index syntax/warn.scrbl
  - cd out
  - git init
  - git config user.name "Travis CI"
  - git config user.email "jackhfirth@gmail.com"
  - git add .
  - git commit -m "Deploy to GitHub Pages"
  - git push --force --quiet "https://${GH_TOKEN}@github.com/jackfirth/syntax-warn.git" master:gh-pages > /dev/null
